//
//  AppColors.swift
//  PubRanker
//
//  Created on 30.11.2025
//  Version 2.0 Design System
//

import SwiftUI

/// PubRanker 2.0 Color System
/// Provides a consistent color palette across the app with Light/Dark mode support
extension Color {

    // MARK: - Primary Colors (Pub Wood Theme)

    /// Primary color - Dark brown (Pub wood theme)
    /// Light: #A0522D (160, 82, 45)
    /// Dark: #CD853F (205, 133, 63)
    /// Note: appPrimary is automatically generated by Xcode from Assets.xcassets
    
    /// Primary color - Light variant
    static let appPrimaryLight = Color(red: 205/255, green: 133/255, blue: 63/255)

    /// Primary color - Dark variant
    static let appPrimaryDark = Color(red: 160/255, green: 82/255, blue: 45/255)

    // MARK: - Secondary Colors (Gold/Beer Theme)

    /// Secondary color - Gold
    /// Light: #FFD700 (255, 215, 0)
    /// Dark: #E5C100 (229, 193, 0)
    /// Note: appSecondary is automatically generated by Xcode from Assets.xcassets

    /// Secondary color - Light variant
    static let appSecondaryLight = Color(red: 255/255, green: 215/255, blue: 0/255)

    /// Secondary color - Dark variant
    static let appSecondaryDark = Color(red: 229/255, green: 193/255, blue: 0/255)

    // MARK: - Accent Colors (Highlight/CTA)

    /// Accent color - Orange
    /// Light: #F15A24 (241, 90, 36)
    /// Dark: #FF7F50 (255, 127, 80)
    /// Note: appAccent is automatically generated by Xcode from Assets.xcassets

    /// Accent color - Light variant
    static let appAccentLight = Color(red: 241/255, green: 90/255, blue: 36/255)

    /// Accent color - Dark variant
    static let appAccentDark = Color(red: 255/255, green: 127/255, blue: 80/255)

    // MARK: - Success/Positive Colors

    /// Success color - Green
    /// Light: #06C14F (6, 193, 79)
    /// Dark: #32CD32 (50, 205, 50)
    /// Note: appSuccess is automatically generated by Xcode from Assets.xcassets

    /// Success color - Light variant
    static let appSuccessLight = Color(red: 6/255, green: 193/255, blue: 79/255)

    /// Success color - Dark variant
    static let appSuccessDark = Color(red: 50/255, green: 205/255, blue: 50/255)

    // MARK: - Background Colors

    /// App background - Neutral
    /// Light: #F0F0F0 (240, 240, 240)
    /// Dark: #1C1C1E (28, 28, 30)
    /// Note: appBackground is automatically generated by Xcode from Assets.xcassets

    /// Background - Light variant
    static let appBackgroundLight = Color(red: 240/255, green: 240/255, blue: 240/255)

    /// Background - Dark variant
    static let appBackgroundDark = Color(red: 28/255, green: 28/255, blue: 30/255)

    /// Secondary background (slightly different from main)
    /// Note: appBackgroundSecondary is automatically generated by Xcode from Assets.xcassets

    // MARK: - Text Colors

    /// Primary text color
    /// Light: #000000 (0, 0, 0)
    /// Dark: #FFFFFF (255, 255, 255)
    /// Note: appTextPrimary, appTextSecondary, and appTextTertiary are automatically generated by Xcode from Assets.xcassets

    // MARK: - Gradients

    /// Primary gradient (brown theme)
    static let gradientPrimary = LinearGradient(
        colors: [appPrimaryDark, appPrimaryLight],
        startPoint: .topLeading,
        endPoint: .bottomTrailing
    )

    /// Secondary gradient (gold theme)
    static let gradientSecondary = LinearGradient(
        colors: [appSecondaryDark, appSecondaryLight],
        startPoint: .topLeading,
        endPoint: .bottomTrailing
    )

    /// Accent gradient (orange theme)
    static let gradientAccent = LinearGradient(
        colors: [appAccentLight, appAccentDark],
        startPoint: .topLeading,
        endPoint: .bottomTrailing
    )

    /// Success gradient (green theme)
    static let gradientSuccess = LinearGradient(
        colors: [appSuccessLight, appSuccessDark],
        startPoint: .topLeading,
        endPoint: .bottomTrailing
    )

    /// Mixed gradient (primary to secondary)
    static let gradientPubTheme = LinearGradient(
        colors: [appPrimaryDark, appSecondaryLight],
        startPoint: .leading,
        endPoint: .trailing
    )

    /// Sunset gradient (accent variations)
    static let gradientSunset = LinearGradient(
        colors: [
            Color(red: 241/255, green: 90/255, blue: 36/255),
            Color(red: 255/255, green: 127/255, blue: 80/255),
            Color(red: 255/255, green: 215/255, blue: 0/255)
        ],
        startPoint: .topLeading,
        endPoint: .bottomTrailing
    )
}

// MARK: - Color Scheme Helper

struct AppColorScheme {
    /// Current color scheme (light/dark)
    @Environment(\.colorScheme) var colorScheme

    /// Returns appropriate color based on current scheme
    func adaptive(light: Color, dark: Color) -> Color {
        colorScheme == .dark ? dark : light
    }
}

// MARK: - Usage Examples & Documentation

/*
 USAGE EXAMPLES:

 // Basic usage
 Text("Hello")
     .foregroundStyle(.appPrimary)

 // Background
 VStack {
     ...
 }
 .background(.appBackground)

 // Gradient background
 Rectangle()
     .fill(.gradientPrimary)

 // Button with primary color
 Button("Action") { }
     .buttonStyle(.borderedProminent)
     .tint(.appPrimary)

 // Card with gradient
 VStack {
     ...
 }
 .background(.gradientPubTheme)

 COLOR USAGE GUIDELINES:

 - Primary (.appPrimary): Navigation bars, main buttons, logo
 - Secondary (.appSecondary): Pub cards, progress bars, headers, highlights
 - Accent (.appAccent): Star ratings, top rank badges, CTA buttons
 - Success (.appSuccess): High ratings, favorite badges, positive feedback
 - Background (.appBackground): App background, windows
 - Text (.appTextPrimary): Main text, labels

 GRADIENTS:

 - gradientPrimary: For primary elements (buttons, headers)
 - gradientSecondary: For highlighted cards, important sections
 - gradientAccent: For call-to-action elements
 - gradientPubTheme: For hero sections, special cards
 - gradientSunset: For celebration/achievement elements
 */
